### ISSUE TITLE
Help us organize this repo.

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#103]
To organize this project in such a way so that the user can find the stuff quickly and  can navigate through the list easily so if you have some ideas comment down below our aim is to make this beginner guide to web development something similar to this 
[OSSU](https://github.com/ossu/computer-science)
[OSSU website](https://ossu.firebaseapp.com)

**Comment by MsWebGirl** [comment]
I would suggest renaming some of your files. The names don't fully represent their content.  For instance, Contributing.md vs Contributors.md. The first one talks of how to contribute and do a pull request. The second is a list of folks who have contributed to this codebase. I would suggest the first file contributing be in with the github resources and create a folder called Github Resources

**Comment by arjunkharbanda** [comment]
Thanks for your suggestion. if you want and can contribute please do it will be appreciated.

**Comment by arjunkharbanda** [comment]
@MsWebGirl  and @alexroseb do you have some suggestion on how we can better organize this repo we currently have a Markdown and a website but we are not able to maintain both @SamirJouni come up with one idea to separate both in different repos. what is your suggestion?

**Comment by alexroseb** [comment]
Using Github Pages and Markdown we only have to keep the .md files uploaded and Jekyll automatically turns them into HTML! Check out http://articles.alexroseb.com/resources to see this in action. I think we should change to this model.

**Comment by sparkle-sparkle** [comment]
> @MsWebGirl and @alexroseb do you have some suggestion on how we can better organize this repo we currently have a Markdown and a website but we are not able to maintain both @SamirJouni come up with one idea to separate both in different repos. what is your suggestion?

I'm wondering: why would you want two repos? If you keep the documentation in the same repo as the code, the changes are bigger that the documentation keeps in sync with the code. Just food for thought 😃

**Comment by Neticx** [comment]
i wass adding some resource

**Comment by arjunkharbanda** [comment]
@Neticx feel free to add as many as you can
