### ISSUE TITLE
convert YouTube.md to a webpage 

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#104]
we need to add `YouTube.md` into` index.html` so if you can and want help please do it will be appreciated.

**Comment by alexroseb** [comment]
Is `index.html` generated automatically from the .md files?

**Comment by arjunkharbanda** [comment]
No, you have to do it manually.

**Comment by alexroseb** [comment]
Follow-up (and referencing your request in #103), I think it could be good to set up a site that draws on the raw .md files to create the whole site - I can do that if it's something you want.

**Comment by arjunkharbanda** [comment]
Can you elaborate how this can be done?

**Comment by alexroseb** [comment]
There are multiple ways! One of the easiest and best-compatible with GitHub.io is to use Jekyll. I’m not at a computer right now but in a few hours I’ll sit down and create a mock-up.

**Comment by alexroseb** [comment]
Check out http://articles.alexroseb.com/resources for the Jekyll site! It uses [branch gh-pages of my fork](https://github.com/alexroseb/resources/tree/gh-pages) and we can change the theme/develop more from there but it's an example.

**Comment by arjunkharbanda** [comment]
Thanks, @EkaanshArora and @alexroseb for your contribution. if you can and want to help we can discuss more in #110  @SamirJouni I need your help too.
