### ISSUE TITLE
Should we create a seprate list of Podcast related to web development? 

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#153]
Should we create a list of podcasts like we have a one YouTube channels let me know? also if you know some good one share them in the comments aswell.

**Comment by dadams89** [comment]
@arjunkharbanda What would you like to be done here? I know of quite a few great Web Dev podcasts!

**Comment by dadams89** [comment]
I can certainly take this.

**Comment by MelanieL** [comment]
@dadams89 I'm happy to help with this too. Where are you with it? I'd like to jump in if I can.

**Comment by arjunkharbanda** [comment]
@dadams89 and @MelanieL  go ahead and send a PR when done.
