### ISSUE TITLE
Extending the list to non-web development resources.

### ISSUE THREAD

**Issue by avidLearnerInProgress** [zero-to-mastery/resources#244]
Since these resources are a good one-stop beginners guide for starting their programming journey, why limit the list for web-development!

We can include topics like:
1. Data Analysis, Machine learning and Artificial Intelligence
2. Mobile App development
3. Cloud Computing

Since JS already exists, there can be separate well-curated lists about other programming languages like Python, Rust, Go etc.

**Comment by arjunkharbanda** [comment]
Will happy to include them too just send a PR
