### ISSUE TITLE
Add a CONTRIBUTING.md Guideline

### ISSUE THREAD

**Issue by UcheSylvester** [zero-to-mastery/resources#257]
As the list of learning resources grows and more people get to use this project, wouldn't it be nice if we had a CONTRIBUTING.md file. This will serve as a guideline, listing out the steps for contributing to this project thus making contributing easier, and encourage developers especially newbies and recent graduates from the ZTM courses to contribute.
I'd be interested to work on this feature if approved. Thank you!

**Comment by MattCSmith** [comment]
@UcheSylvester Sounds like a great idea, go ahead and implement this 👍

**Comment by UcheSylvester** [comment]
Wow! Thank you so much for approving, I will work on it over the weekend! 💪

**Comment by arjunkharbanda** [comment]
@UcheSylvester  sorry was not able to reply earlier and as @MattCSmith said go ahead and implement and let us know if you need any help and send PR when done. Thanks, for your contribution to this project.

**Comment by UcheSylvester** [comment]
Thank you so much @arjunkharbanda.
Apologies for not being able to reply earlier, I have been working on some code challenges for the courses I'm taking with Pluralsight through the Google Certification Scholarship that I have not been able to implement this. I just start working on it, and will definitely reach out if need be. 
Thank you

**Comment by UcheSylvester** [comment]
@MattCSmith @arjunkharbanda, I just opened a pull request with regard to this issue (creating a CONTRIBUTING.md file). Please review and merge if criteria are met. 
Thank you

**Comment by arjunkharbanda** [comment]
Thanks, @UcheSylvester for your effort.
