### ISSUE TITLE
Link this repo to zero-to-mastery website

### ISSUE THREAD

**Issue by agpt8** [zero-to-mastery/resources#267]
zero-to-mastery website has a resources section. It would be nice if this repo and the one present there could be merged or integrated somehow. I opened a similar issue in that repo. This will help others to look at just one place for all the resources. See [this](https://github.com/zero-to-mastery/zero-to-mastery-website/issues/173#issue-470235490)

**Comment by MMAcode** [comment]
Link from here to there exists @agpt8 . See in README.dm file on the top: 

> Useful Resources for Developers
A list of student collated resources deemed to be useful for every developer and catergorised. Andrei has a hand picked list of his favourite resources which you can find **here**.>

**Comment by arjunkharbanda** [comment]
Thanks, @MMAcode will be closing this issue now.
