### ISSUE TITLE
Page Build Failed 

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#294]
![image](https://user-images.githubusercontent.com/15190745/66260618-697bfc80-e7de-11e9-8620-16b72322bcc9.png)
Need to fix this ASAP.

**Comment by digikin** [comment]
So... let me take a look.

**Comment by arjunkharbanda** [comment]
@digikin sure what kind of info do you need I can provide you also if possible fork this repo and run it on your local machine.

**Comment by arjunkharbanda** [comment]
@SamirJouni @MattCSmith please take a look at this

**Comment by arjunkharbanda** [comment]
#296
