### ISSUE TITLE
SEO OPTIMIZATION

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#306]
Any tips to improve SEO and make it more search friendly?

**Comment by akashjoffl** [comment]
Hi Arjun,

Try out the following online tools to improve the SEO for increasing the viewers amount.

https://kwfinder.com/
https://www.hubspot.com/blog-topic-generator

Hope it helps 👍

**Comment by arjunkharbanda** [comment]
Hey Akash thanks for your suggestions will definitely take a look.

**Comment by sophiabrandt** [comment]
@arjunkharbanda Are you stil interested in tackling this, or should we open the issue for other contributors?

**Comment by arjunkharbanda** [comment]
@sophiabrandt  it's already open to everyone if you have any ideas please share.

**Comment by sophiabrandt** [comment]
Just wanted to make sure, because others will most likely assume that you want to tackle it. At least it sounded to me like you wanted to spear-head the effort.
Thanks for clarifying. :+1:

**Comment by arjunkharbanda** [comment]
In this project, everything is open to everyone sorry if it sounded like that my intentions were to kickstart the discussion that is why I started this at time of hacktorberfest because that is when we receive peak traffic😁

**Comment by arjunkharbanda** [comment]
@sophiabrandt  thanks for taking the time and contributing to this project much appreciated

**Comment by Nelson877** [comment]
please i am new in here

**Comment by arjunkharbanda** [comment]
@Nelson877  What you want?
