### ISSUE TITLE
Microsoft Virtual Academy shut down

### ISSUE THREAD

**Issue by ArunJose** [zero-to-mastery/resources#366]
Microsoft Virual Academy has been shut down. Its replacement Microsoft Learn is focused on videos about Microsoft proprietary technologies.

**Comment by sophiabrandt** [comment]
Removed with https://github.com/zero-to-mastery/resources/commit/e3ab7d10e94b47a3b5fcd672baa5bb7e5d2f74fb.
Thanks for pointing it out.
