### ISSUE TITLE
Should we add a CSS Resources category?

### ISSUE THREAD

**Issue by frostillicus** [zero-to-mastery/resources#384]
Currently there are a lot of CSS resources in the Web Design Resources. Although related to web design, these resources may fit better in a **CSS Resources** category.

**Comment by DiscoverSquishy** [comment]
@frostillicus Give it a try! It will definitely be cleaner; here's a guide if you need it :)
[Guide Link](https://opensource.guide/how-to-contribute/)

**Comment by frostillicus** [comment]
Alright, I've created a pull request. It's worth noting that some resources are very relevant to both CSS and web design, and they could really go in either category. There were a few css-related links that I kept in Web Design Resources (for example, CSS Color Names works well in the Color Palettes section).

**Comment by DiscoverSquishy** [comment]
Great work @frostillicus, thanks for your suggestion and action 😄
