### ISSUE TITLE
[Up for Grabs/Enhancement]: Add a link to `Contributing_to_GitHub.md` to README

### ISSUE THREAD

**Issue by sophiabrandt** [zero-to-mastery/resources#427]
We have a file called `Contributing_to_GitHub.md`.
I suggest adding a link to that file in the section "Contributing" in README.md

For example, in `README.md`:

```md
## Contributing

- [Contributing to GitHub](Contributing_to_GitHub.md): blablabla, text

- You are always welcome to contribute to this project, kindly visit our [**Contributors' Guide**](https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md) before opening a pull request

// more text

```

Don't forget to add your name to `CONTRIBUTORS.md`, too!

**Comment by morrme** [comment]
Would it flow smoother to have a message *after* the "You are welcome..." line, like:

"First time contributing to open source? Awesome! Read more about the process in [Contributing to GitHub](link)

**Comment by sophiabrandt** [comment]
@morrme Sure, that sounds good! :+1:
