### ISSUE TITLE
Add a new resource category: API

### ISSUE THREAD

**Issue by aneta-s** [zero-to-mastery/resources#436]
I'd like to add a new category for my resource: API. In the Web Dev course there is a whole section how to integrate an API to a website i.e Skyscanner. Andrei says it is important to know how to read an API documentation wisely and recognise how to underly principles. This is a link I want to add to this category.
https://scottbarstow.com/apis-how-to-read-and-understand-documentation/

**Comment by sophiabrandt** [comment]
Good idea. Go ahead. I think it's a good section to have.

**Comment by DiscoverSquishy** [comment]
Hiya @aneta-s, I'm glad you want to make an addition to this resource.
Here is a little guide for this repo for if you want to add that link to this resource, https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md

Best of luck! Make sure you tag this resource #436 in your PR so it automatically closes :)

**Comment by DiscoverSquishy** [comment]
@aneta-s Can I just ask if you will take care of this? If not we can put this issue up for other people to cover this issue :).

**Comment by arjunkharbanda** [comment]
@aneta-s  Please Reply and @sophiabrandt  @DiscoverSquishy we should make this issue compulsory so that everyone can contribute

**Comment by Prajakta-collab** [comment]
i am not able to make PR on this issue. can u help me out ? it is showing some conflict like that

**Comment by pulamusic** [comment]
@Prajakta-collab Make sure your forked copy of the Resources repo is up to date before you make a pull request. GitHub repos won't allow you to register a pull request if your fork is not current. Just do 'git pull' first, updating any changes someone else has made since you last pulled the repo. This will not damage any work you have done in your forked copy. Then push do your regular stage/commit/push business. At that point you should be able to do a pull request.

**Comment by aneta-s** [comment]
> @aneta-s Please Reply and @sophiabrandt @DiscoverSquishy we should make this issue compulsory so that everyone can contribute

I'm so sorry for a late reply @sophiabrandt and @DiscoverSquishy am I free to add the resources and close the issue yet?

**Comment by sophiabrandt** [comment]
Yes, @aneta-s , feel free to go ahead.

**Comment by sophiabrandt** [comment]
Closed by #552 .
