### ISSUE TITLE
Game Development Resources

### ISSUE THREAD

**Issue by vivekboss99** [zero-to-mastery/resources#524]
i can include the resources for game development, categorised as websites, documentations, youtube, etc.

**Comment by vivekboss99** [comment]
I PR'ed the Resources but getting an error.

**Comment by arjunkharbanda** [comment]
@SamirJouni @MattCSmith can you guys look into this

**Comment by vivekboss99** [comment]
PR number #525

**Comment by vivekboss99** [comment]
@arjunkharbanda thanks for reaching out, for some reason there is no merge conflicts but the build is failing when i try to pull request.

**Comment by vivekboss99** [comment]
@sophiabrandt this is the issue for the pull request #525

**Comment by sophiabrandt** [comment]
I'm fine with adding a new category, but want to wait for a second opinion from a maintainer.

**Comment by arjunkharbanda** [comment]
No Issue with adding a new category but you PR has to pass Travis checks

**Comment by vivekboss99** [comment]
@arjunkharbanda i'm not able to figure out why travis checks are not passing,please guide me.

**Comment by arjunkharbanda** [comment]
Well I don't know either maybe submit a new PR and will see

**Comment by sophiabrandt** [comment]
I've merged the PR. If something doesn't work, we can fix it later. See PR #525 .
