### ISSUE TITLE
Django web framework resource

### ISSUE THREAD

**Issue by atharv123-wq** [zero-to-mastery/resources#559]
I can add a resource for django web framework

**Comment by sophiabrandt** [comment]
How many resources do you want to add? Would that not be better suited for the Python resource?

**Comment by atharv123-wq** [comment]
just 1 resource for django framework yep can be added in python resource

**Comment by sophiabrandt** [comment]
Allright, I will close this issue for now. You can go ahead and add your resource to the `Python.md` file.
If you want to add more resources later and feel that a separate category is needed, feel free to open a new issue.
Thank you.
