### ISSUE TITLE
Create Free photo/Images websites under Web design resources

### ISSUE THREAD

**Issue by frankiefab100** [zero-to-mastery/resources#635]
create a category for websites with free images for web design and development

**Comment by DiscoverSquishy** [comment]
@frankiefab100 Do you want to create a PR for this category?

**Comment by frankiefab100** [comment]
Yes, I would like to.

**Comment by DiscoverSquishy** [comment]
@frankiefab100 Alrighty great, then feel free to create a PR with 'closes #635' in the messages.

**Comment by sophiabrandt** [comment]
Looks like a dead issue to me.
