### ISSUE TITLE
Couple of dead links

### ISSUE THREAD

**Issue by alexeigud** [zero-to-mastery/resources#648]
CSS Visual Dictionary hyperlink forwards to a potentially malicious spam landing page. I would take a screenshot but that page scares me. Also on the CSS Zen Garden home page, the hyperlink on the top right side bar also references a web page that is unreachable.

**Comment by DiscoverSquishy** [comment]
@alexeigud Are you able to create a PR to fix the dead links?

**Comment by alexeigud** [comment]
Only for CSS Visual Dictionary. I cannot fix a link on someone else's website.

**Comment by DiscoverSquishy** [comment]
I'll keep this closed for now then, if we can't control others' websites then there's no need to attempt to fix it from our end.
