### ISSUE TITLE
Allthefreestocks link has many broken links

### ISSUE THREAD

**Issue by motheroftrouble** [zero-to-mastery/resources#661]
Under Web Design Resources: images & video (the very first resource) has many links that are inoperable. My question is this. Do we keep the master link for the few links that work? Or do we remove that link and add any that were on it that still work? I wonder too if any of the links listed in that one are listed elsewhere. When I have more free time I will go through the links and validate all that work and submit edit suggestions as I see fit. Unless someone else wants to beat me to it.

**Comment by arjunkharbanda** [comment]
what do you mean about links are Inoperable? do you mean dead links? if so we replace those with working links if possible
also if you want to take a shot at it go for it and send PR when done.

**Comment by motheroftrouble** [comment]
Yes broken links. The link to that resource itself works fine but once you
get in there it has a whole bunch of links inside it that don't work so I'm
not sure if we can fix that because it's hosted by someone else.also I am
eager to work on it however have a pretty full plate right now so I'll try
to but I'm not sure if I'll get to it in the next month or not.
