### ISSUE TITLE
Broken bullet points in cheatSheets.md

### ISSUE THREAD

**Issue by tejasmorkar** [zero-to-mastery/resources#662]
The last 7 bullet points in cheatSheets.md are not in the correct syntax of Markdown. 

## Screenshot

![image](https://user-images.githubusercontent.com/35477326/106095019-0cd1ed00-6159-11eb-82d0-ff13430d6364.png)

## Steps to reproduce

- Open the link - https://zero-to-mastery.github.io/resources/cheatSheets.html
- Scroll down to the last 7 bullet points

## Possible fix

Insert a space between the hyphen and text for correct Markdown syntax

### I would like to fix this and create a pull request for the same.

**Comment by arjunkharbanda** [comment]
Go ahead submit a PR when you are done. Thanks for your contribution.
