### ISSUE TITLE
Update Travis CI  code 

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#711]
Can some take a look at Travis CI code? we are seeing a lot of failed builds lately I don't know why? earlier @SamirJouni  and @DiscoverSquishy  worked on that so if any of two can help us again that would be great.

**Comment by sophiabrandt** [comment]
Seems like it's fixed? @arjunkharbanda

**Comment by arjunkharbanda** [comment]
IDK should we add hacktoberfest tag I want to check it and make necessary changes if required .

**Comment by sophiabrandt** [comment]
@arjunkharbanda I'm not sure if changes are needed as Travis seems to be working fine for months?

If you can pinpoint an error and propose a solution, feel free.

**Comment by arjunkharbanda** [comment]
Ok I am closing this
