### ISSUE TITLE
Add a `WebDevCourses.md` file

### ISSUE THREAD

**Issue by Memphis1983** [zero-to-mastery/resources#738]
Can we add a new markdown file to add links to Web Development Courses?

**Comment by arjunkharbanda** [comment]
We already have a moocs.md  maybe we can change it's name and make it more generic.

**Comment by Memphis1983** [comment]
@arjunkharbanda yes we definitely can, thank you. It has similar resources. I Will wait for the green light then :)

**Comment by arjunkharbanda** [comment]
Will have to make some changes will let you know when it's done

**Comment by Memphis1983** [comment]
Sounds good thank you @arjunkharbanda

**Comment by sophiabrandt** [comment]
@Memphis1983 feel free to add your resources to `FreeOnlineCourses.md` now. Thank you for your contribution.

**Comment by Memphis1983** [comment]
Thank you
