### ISSUE TITLE
Should we rename moocs .md?

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#739]
@AvidCoder101 @sophiabrandt  should we rename moocs.md to just free online courses or should create section altogether?

_Originally posted by @arjunkharbanda in https://github.com/zero-to-mastery/resources/pull/734#issuecomment-932741840_

**Comment by sophiabrandt** [comment]
MOOCs are technically not free. They are free to attend, but you need to pay for the license.

That could be confusing. :shrug:

**Comment by arjunkharbanda** [comment]
We can add sub sections most of online course are free to consume and some even provide certificate for free. It's not like you have to pay upfront like in some cases udemy frontend master etc

**Comment by sophiabrandt** [comment]
Allright, let's not overcomplicate things. I'm going ahead and make necessary changes.
