### ISSUE TITLE
Design Tools

### ISSUE THREAD

**Issue by mikegulline** [zero-to-mastery/resources#790]
Great resources list!

I have been following the [Design Tools Survey](https://uxtools.co/survey-2021) for several years and it has helped me evolve my front end stack tremendously!

I would like to ad a Design Tools subhead to the **WebDesignResources.md** list to include the 2021 survey.

Let me know if you think this is a good fit and I will contribute!

Thanks for all the great infos!

**Comment by sophiabrandt** [comment]
Sure, thank you for your contribution. I will close this issue, but feel free to add the relevant section.
