### ISSUE TITLE
Broken video link on AlgorithmsDataStructures.md

### ISSUE THREAD

**Issue by antonio-erick** [zero-to-mastery/resources#819]
The following link doesn't work anymore: [Data Structures and algorithms](https://www.youtube.com/watch?v=lxja8wBwN0k&list=PLKKfKV1b9e8ps6dD3QA5KFfHdiWj9cB1s)

**Comment by sophiabrandt** [comment]
If you like, you can fix this (or someone else). Thank you.

**Comment by donmarvex** [comment]
Hello @antonio-erick , has a pull request been made to fix this issue?

**Comment by sophiabrandt** [comment]
There is no movement on this issue, so I will close this for now.
