### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by Dharmik48** [zero-to-mastery/resources#847]
Having a PR template can really help new contributors while raising a PR. With a PR template, new contributors have to worry less about adding proper descriptions to PR and rather focus on actually contributing new resources.

Also, it can help to keep all PRs consistent in the project.

**Comment by donmarvex** [comment]
Hello @Dharmik48 , yes, indeed a pull request template is very beneficial. 
- First of all, can you identify a specific repository within ZTM that could need a pull request template.
- After identifying the repository, also determine if multiple pull request templates would be needed for certain types of pull requests.
- Any other useful additions that could be added to the template.

I'd also like to hear your initial thoughts on this and what you have in mind. Then we can proceed to assign the task to you or to another member/contributor.

**Comment by Dharmik48** [comment]
> a specific repository within ZTM that could need a pull request template apart from this one

You don't want a PR template for this repository?

**Comment by donmarvex** [comment]
> > a specific repository within ZTM that could need a pull request template apart from this one
> 
> You don't want a PR template for this repository?

I was just asking if you had other ideas for other repositories apart from this one also. Definitely, yes

**Comment by donmarvex** [comment]
But let's focus on this one and let me hear your initial thoughts about the contents of the pull request template.

**Comment by Dharmik48** [comment]
> > > a specific repository within ZTM that could need a pull request template apart from this one
> > 
> > 
> > You don't want a PR template for this repository?
> 
> I was just asking if you had other ideas for other repositories apart from this one also. Definitely, yes

Okay got it

**Comment by Dharmik48** [comment]
> But let's focus on this one and let me hear your initial thoughts about the contents of the pull request template.

Okay so in this repository, most PRs will be of new resources, so I think these should be the template's content:

- Resource name and link
- Why so they think this is a good resource
- A GitHub repo of the resource (if any)

**Comment by donmarvex** [comment]
> > But let's focus on this one and let me hear your initial thoughts about the contents of the pull request template.
> 
> Okay so in this repository, most PRs will be of new resources, so I think these should be the template's content:
> 
> * Resource name and link
> * Why so they think this is a good resource
> * A GitHub repo of the resource (if any)

Alright, this looks great. So right off the bat, any contributor/reviewer is able to see this instead of having to check the changed files tab, copy/paste the link to check out the resource or check the branch and click the link to do this.
This would save time for the reviewer. It's a great addition. 
I think the same description as included in the markdown file can be added as a fourth item in addition to why they think it's a good resource. 

Now that you have outlined these items for the template, do you want to work on this?

**Comment by Dharmik48** [comment]
Ya sure! I'd love to work on it.

**Comment by donmarvex** [comment]
> Ya sure! I'd love to work on it.

I have assigned you to work on this

**Comment by Dharmik48** [comment]
Sure thing! I'll get to work as soon as I can

**Comment by Dharmik48** [comment]
See, when I raised this new PR, it was automatically filled with the template contents!

![image](https://user-images.githubusercontent.com/64529217/176435444-60d0aaa1-021f-49c0-b892-12974954c26f.png)
