### ISSUE TITLE
Suggestion: Favicon

### ISSUE THREAD

**Issue by GaryBleasdale** [zero-to-mastery/resources#864]
Minor suggestion: that we include a favicon to the website to give the site a more 'complete' feel, and let the tab look more at home among other tabs in the browser.  Would be happy to work on this simple, but I think worthwhile, upgrade.

**Comment by donmarvex** [comment]
> Minor suggestion: that we include a favicon to the website to give the site a more 'complete' feel, and let the tab look more at home among other tabs in the browser. Would be happy to work on this simple, but I think worthwhile, upgrade.

That would be great @GaryBleasdale . You can go ahead and work on this!

**Comment by sophiabrandt** [comment]
I am assuming that @GaryBleasdale is not interested in this anymore, so if anyone else has interest in adding the favicon, feel free to comment here.

**Comment by EduardoDoSomeCode** [comment]
Hello,  I am interested in contributing to the project and would like to submit a pull request to add the Favicon Icon feature, can i still submit my pull request ?

**Comment by EduardoDoSomeCode** [comment]
#975

**Comment by sophiabrandt** [comment]
#975 merged - thanks @EduardoDoSomeCode
