### ISSUE TITLE
Add New category that includes Blockchain and web3 recourses  

### ISSUE THREAD

**Issue by Bhavya1912** [zero-to-mastery/resources#888]
Business runs on information. The faster it’s received and the more accurate it is, the better. Blockchain(web3) is ideal for delivering that information because it provides immediate, shared and completely transparent information stored on an immutable ledger that can be accessed only by permissioned network members.
I can work on this please assign this to me if you like it

**Comment by sophiabrandt** [comment]
If you're still interested in this, feel free to add a new category

**Comment by sophiabrandt** [comment]
I'm closing this issue.
@bellsofaba please see comment to your pull request.
