### ISSUE TITLE
Adding an Open Source Category

### ISSUE THREAD

**Issue by CBID2** [zero-to-mastery/resources#893]
Hello there! :) I'm thinking of adding an Open Source category to this file. It would be a great tool for coders of all experience levels to find ways to develop their soft skills outside of doing coding tutorials, courses, etc.

**Comment by rhinoxD** [comment]
I second that, adding an Open Source category will help our fellow developers especially beginners to contribute to large scale open source projects. It'll be a great way to get real world software development experience from the comfort of your home and will enhance your resume ✨.

**Comment by CBID2** [comment]
Hi, @rhinoxD! :) Sorry for the delay! :) I've been immersing myself in the open source community and am now back with resources. Check out my pull request, #924! :)

**Comment by l-white** [comment]
@CBID2 @rhinoxD This has been added! Thank you for your contribution @CBID2 It's a great idea.
