### ISSUE TITLE
Fix,typos grammatical mistake etc 

### ISSUE THREAD

**Issue by arjunkharbanda** [zero-to-mastery/resources#96]
If you are a Grammar Nazi and want to help, please look into our for typos and grammatical mistakes and fix them. It will be much appreciated.

**Comment by JorgeRangelJ** [comment]
Hi,` very pleased to collaborate

**Comment by jaskaran714** [comment]
> If you are a Grammar Nazi and wanted to help please look into our repo for typos and grammar mistake and fix them. It will be much appreciated

`If you are a Grammar Nazi and want to help, please look into our for typos and grammatical mistakes and fix them. It will be much appreciated.`

**Comment by arjunkharbanda** [comment]
@iamxlr8 Thanks for your effort and @jaskaran714 if you are so good why don't you contribute instead showing off here.

**Comment by OzTack** [comment]
Just found CSS "DINNER" - it is actually CSS-Diner . Edited and pull request in system.
